### ISSUE TITLE
Isn't there a better way?

### ISSUE THREAD

**Issue by borfast** [InderdeepBajwa/gitid#4]
I may be missing the point but it seems to me that this is a little overly complex and there may be a better way to achieve the same thing.

You can specify [different configuration options per repository](https://www.borfast.com/blog/2021/02/27/how-to-override-and-share-git-configuration-options-between-multiple-directories/) and in those you could set the `core.sshCommand` to use a different key file.

In the linked blog post I talk about configuring email addresses and GPG signing keys but you can just as easily set a different SSH key with something like this:

```
core.sshCommand = ssh -i ~/.ssh/id_rsa_example -F /dev/null" git@github.com:example/example.git
```

Am I missing something?

**Comment by InderdeepBajwa** [comment]
Thank you for your question! Indeed, the method you have suggested with core.sshCommand is an efficient solution when it aligns with the user's needs. I myself have dealt with identity files in the past and found it to be repetitive and cumbersome, especially when switching between devices where reconfiguration is necessary. Moreover, I have seen beginners perceive this as complex.

The CLI tool that we've developed here aims to cater to two key objectives:

1. Offer a seamless and automated solution to generate SSH keys, as well as add, list, and switch identities, all without needing the user to edit git config or SSH config files manually.

2. It abstracts the complexities associated with ssh-keygen and git config commands. The idea is to present a user-friendly interface that simplifies identity management for those who do not wish to get into the nitty-gritty of git configuration management.

Furthermore, while using the core.sshCommand approach can be advantageous, it could result in a disjointed configuration setup if employed along with other methods, such as the IdentityFile directive of SSH configuration.

I agree that your suggestion offers a valuable and alternative approach, this CLI tool can still be extremely beneficial for those wanting to automate and simplify their tasks related to identity management.

**Comment by borfast** [comment]
Fair enough, I can see your points :slightly_smiling_face: 
Thanks for replying! :slightly_smiling_face:
