### ISSUE TITLE
[feature request] gitid show <id_name> to show ssh key

### ISSUE THREAD

**Issue by epinoia-au** [InderdeepBajwa/gitid#7]
This is just me being lazy but would be would be sweet to be able to do gitid show <id_name> and output the ssh key for easy copying.

**Comment by InderdeepBajwa** [comment]
Thank you for the feature request! Introducing it very shortly here: https://github.com/InderdeepBajwa/gitid/pull/8

**Comment by InderdeepBajwa** [comment]
Addressed in: https://github.com/InderdeepBajwa/gitid/pull/10
